### Anaphora resolution

1) Get the pretrained model of FastText from https://fasttext.cc/docs/en/english-vectors.html

2) At the pytorch develop a model, that is a feed forward neural network that consists of three layers, an input layer of size 600, a first layer of size 300, a second layer of 80 and an output layer with two units, all layers have regularization and dropout. The activation function on all layers is ReLU

![scheme.jpg](attachment:scheme.jpg)

In [3]:
import pandas as pd

In [4]:
df_dev = pd.read_csv('gap-development.tsv',sep='\t')

The task is to identify the target of a pronoun within a text passage. The source text is taken from Wikipedia articles. In the dataset, there are labels of the pronoun and two candidate names to which the pronoun could refer. An algorithm should be capable of deciding whether the pronoun refers to name A, name B, or neither.  
There are the following columns for analysis:
* ID - Unique identifier for an example (Matches to Id in output file format);
* Text - Text containing the ambiguous pronoun and two candidate names (about a paragraph in length);
* Text - Text containing the ambiguous pronoun and two candidate names (about a paragraph in length);
* Pronoun - The target pronoun (text);
* Pronoun-offset The character offset of Pronoun in Text;
* A - The first name candidate (text);
* A-offset - The character offset of name A in Text;
* B - The second name candidate;
* B-offset - The character offset of name B in Text;
* URL - The URL of the source Wikipedia page for the example;

In [5]:
df_dev

ID                                               Text  \
0        development-1  Zoe Telford -- played the police officer girlf...   
1        development-2  He grew up in Evanston, Illinois the second ol...   
2        development-3  He had been reelected to Congress, but resigne...   
3        development-4  The current members of Crime have also perform...   
4        development-5  Her Santa Fe Opera debut in 2005 was as Nuria ...   
...                ...                                                ...   
1995  development-1996  Faye's third husband, Paul Resnick, reported t...   
1996  development-1997  The plot of the film focuses on the life of a ...   
1997  development-1998  Grant played the part in Trevor Nunn's movie a...   
1998  development-1999  The fashion house specialised in hand-printed ...   
1999  development-2000  Watkins was a close friend of Hess' first wife...   

     Pronoun  Pronoun-offset                  A  A-offset  A-coref  \
0        her             274     Cheryl Cassidy       191     True   
1        His             284          MacKenzie       228     True   
2        his             265            Angeloz       173    False   
3        his             321               Hell       174    False   
4        She             437  Kitty Oppenheimer       219    False   
...      ...             ...                ...       ...      ...   
1995     her             433             Nicole       255    False   
1996     her             246          Doris Chu       111    False   
1997     she             348              Maria       259     True   
1998     She             284              Helen       145     True   
1999     her             373          Elizabeth       293    False   

                    B  B-offset  B-coref  \
0             Pauline       207    False   
1       Bernard Leach       251    False   
2          De la Sota       246     True   
3     Henry Rosenthal       336     True   
4              Rivera       294     True   
...               ...       ...      ...   
1995             Faye       328     True   
1996              Mei       215     True   
1997  Imelda Staunton       266    False   
1998  Suzanne Bartsch       208    False   
1999          Watkins       347     True   

                                                    URL  
0     http://en.wikipedia.org/wiki/List_of_Teachers_...  
1         http://en.wikipedia.org/wiki/Warren_MacKenzie  
2     http://en.wikipedia.org/wiki/Jos%C3%A9_Manuel_...  
3             http://en.wikipedia.org/wiki/Crime_(band)  
4           http://en.wikipedia.org/wiki/Jessica_Rivera  
...                                                 ...  
1995          http://en.wikipedia.org/wiki/Faye_Resnick  
1996              http://en.wikipedia.org/wiki/Two_Lies  
1997  http://en.wikipedia.org/wiki/Sir_Andrew_Aguecheek  
1998           http://en.wikipedia.org/wiki/Helen_David  
1999         http://en.wikipedia.org/wiki/Linda_Watkins  

[2000 rows x 11 columns]

In [6]:
df_val = pd.read_csv('gap-validation.tsv',sep='\t')

In [7]:
df_val

ID                                               Text  \
0      validation-1  He admitted making four trips to China and pla...   
1      validation-2  Kathleen Nott was born in Camberwell, London. ...   
2      validation-3  When she returns to her hotel room, a Liberian...   
3      validation-4  On 19 March 2007, during a campaign appearance...   
4      validation-5  By this time, Karen Blixen had separated from ...   
..              ...                                                ...   
449  validation-450  He then agrees to name the gargoyle Goldie, af...   
450  validation-451  Disgusted with the family's ``mendacity'', Bri...   
451  validation-452  She manipulates Michael into giving her custod...   
452  validation-453  On April 4, 1986, Donal Henahan wrote in the N...   
453  validation-454  Pleasant explains Vassey's guilty conscience m...   

    Pronoun  Pronoun-offset                   A  A-offset  A-coref  \
0       him             256  Jose de Venecia Jr       208    False   
1       She             185               Ellen       110    False   
2       his             435     Jason Scott Lee       383    False   
3        he             333           Reucassel       300     True   
4       she             427        Finch Hatton       290    False   
..      ...             ...                 ...       ...      ...   
449      He             305              Lucien       252    False   
450     she             365              Maggie       242    False   
451     she             306            Scarlett       255    False   
452     her             330                Aida       250    False   
453     him             282              Vassey       234     True   

                 B  B-offset  B-coref  \
0           Abalos       241    False   
1         Kathleen       150     True   
2            Danny       406     True   
3           Debnam       325    False   
4    Beryl Markham       328     True   
..             ...       ...      ...   
449           Abel       264    False   
450            Mae       257    False   
451          Alice       291     True   
452     Miss Millo       294     True   
453         Denton       255    False   

                                                   URL  
0    http://en.wikipedia.org/wiki/Commission_on_Ele...  
1           http://en.wikipedia.org/wiki/Kathleen_Nott  
2    http://en.wikipedia.org/wiki/Hawaii_Five-0_(20...  
3         http://en.wikipedia.org/wiki/Craig_Reucassel  
4      http://en.wikipedia.org/wiki/Denys_Finch_Hatton  
..                                                 ...  
449    http://en.wikipedia.org/wiki/Goldie_(DC_Comics)  
450  http://en.wikipedia.org/wiki/Cat_on_a_Hot_Tin_...  
451  http://en.wikipedia.org/wiki/Michael_Moon_(Eas...  
452          http://en.wikipedia.org/wiki/Aprile_Millo  
453          http://en.wikipedia.org/wiki/Small_Crimes  

[454 rows x 11 columns]

In [8]:
from gensim.models import KeyedVectors

# Creating the model
## Takes a lot of time depending on the vector file size 
en_model = KeyedVectors.load_word2vec_format('wiki-news-300d-1M.vec')

In [25]:
import torch
from torch import nn
import torch.nn.functional as F

class MyAnaphoraNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        
        # define the layers
        self.layers = nn.Sequential(
            nn.Linear(600, 300),
            nn.Dropout(0.3),
            nn.ReLU(),
            nn.Linear(300, 80),
            nn.Dropout(0.3),
            nn.ReLU(),
            nn.Linear(80, 2),
            nn.Dropout(0.3),
            nn.ReLU()
        )
    
    def forward(self, x):
        # forward pass
        x = self.layers(x)
        return x

# instantiate the model
anmodel = MyAnaphoraNetwork()

# print model architecture
print(anmodel)

MyAnaphoraNetwork(
  (layers): Sequential(
    (0): Linear(in_features=600, out_features=300, bias=True)
    (1): Dropout(p=0.3, inplace=False)
    (2): ReLU()
    (3): Linear(in_features=300, out_features=80, bias=True)
    (4): Dropout(p=0.3, inplace=False)
    (5): ReLU()
    (6): Linear(in_features=80, out_features=2, bias=True)
    (7): Dropout(p=0.3, inplace=False)
    (8): ReLU()
  )
)


In [22]:
from nltk import tokenize
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n|\r', ' ', text)
    text = re.sub(r' +', ' ', text)
    text = text.strip()
    return text

def simple_tokenizer(text, pronoun, candidate_a, candidate_b):
    
    
    
    cleantxt = clean_text(text)
    txt = []
    txt.append(pronoun)
    txt.append(candidate_a)
    txt.append(candidate_b)
    toktxt = tokenize.word_tokenize(cleantxt)
    txt = txt + toktxt
    
    tokenized_text = []
    
    for word in txt:
        try:
            word_index = en_model.wv.vocab[word].index
            tokenized_text.append(word_index)
        except KeyError:
            continue
            
    while len(tokenized_text) < 600:
        tokenized_text.append(0)
    vec = torch.Tensor([tokenized_text])
    
    return vec.view(1, -1)



def make_target(label, label_to_ix):
    #print(label_to_ix[str(label['A'])])
    #print([label_to_ix[str(label['A'])], label_to_ix[str(label['B'])] ] )
    return torch.LongTensor([[ label_to_ix[str(label['A'])], label_to_ix[str(label['B'])] ]])

label_to_ix = {"True": 1, "False": 0}

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#loss_function = nn.NLLLoss()
b = nn.MSELoss()
a = nn.CrossEntropyLoss()
lossfxn = nn.CrossEntropyLoss()
lossf = nn.MultiLabelMarginLoss()
optimizer = optim.SGD(anmodel.parameters(), lr=0.1)

X = df_dev


# Usually you want to pass over the training data several times.
# 100 is much bigger than on a real data set, but real datasets have more than
# two instances.  Usually, somewhere between 5 and 30 epochs is reasonable.
for epoch in range(100):
    for row in df_dev.loc[:100 , :].values:
        txt = row[1] #row['Text']
        pronoun = row[2] #row['Pronoun']
        ca = row[4] #row['A']
        cb = row[7]#row['B']
        label = {}
        label['A'] = row[6] #row['A-coref']
        label['B'] = row[9] #row['B-coref']
        
        # Step 1. Remember that PyTorch accumulates gradients.
        # We need to clear them out before each instance
        anmodel.zero_grad()

        # Step 2. Make our BOW vector and also we must wrap the target in a
        # Tensor as an integer. For example, if the target is SPANISH, then
        # we wrap the integer 0. The loss function then knows that the 0th
        # element of the log probabilities is the log probability
        # corresponding to SPANISH
        bow_vec = simple_tokenizer(txt, pronoun, ca, cb)
        target = make_target(label, label_to_ix)
        
        
        
        # Step 3. Run our forward pass.
        log_probs = anmodel(bow_vec)
        #print('log_probs', log_probs.view(2))
        #print('target',target.view(2))
        # Step 4. Compute the loss, gradients, and update the parameters by
        # calling optimizer.step()
        #lossf(x, y)
        loss = lossf(log_probs, target) #lossfxn(log_probs.view(2), target.view(2))
        #print(loss) # outputs tensor(2.4402)
        
        # loss_a = a(log_probs[0], target[0])
        #loss_b = b(log_probs[1], target[1])
        #loss = loss_a + loss_b
        # loss = loss_function(log_probs, target)
        loss.backward()
        optimizer.step()

/home/sultan/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).


In [27]:
with torch.no_grad():
    for row in df_val.loc[:5 , :].values:
        txt = row[1] #row['Text']
        pronoun = row[2] #row['Pronoun']
        ca = row[4] #row['A']
        cb = row[7]#row['B']
        label = pd.DataFrame()
        label['A'] = row[6] #row['A-coref']
        label['B'] = row[9] #row['B-coref']
        
        bow_vec = simple_tokenizer(txt, pronoun, ca, cb)
        log_probs = anmodel(bow_vec)
        print(log_probs)

tensor([[   0.0000, 2189.6782]])
tensor([[0., 0.]])
tensor([[0., 0.]])
tensor([[5382.6147, 4566.9893]])
tensor([[    0.0000, 15980.5352]])
tensor([[14349.7656,     0.0000]])


/home/sultan/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
